include::ROOT:partial$attributes.adoc[]
[[getting-started-system-requirements]]
== System Requirements
By default, Spring Boot {spring-boot-version} requires http://www.java.com[Java 7] and
Spring Framework {spring-version} or above. You can use Spring Boot with Java 6 with some
additional configuration. See xref:howto:howto-build.adoc#howto-use-java-6[howto-use-java-6] for more details.

Explicit build support is provided for the following build tools:

|===
|Build Tool |Version

|Maven
|3.2+

|Gradle
|[2.9, 3.x]
|===

TIP: Although you can use Spring Boot with Java 6 or 7, we generally recommend Java 8 if
at all possible.

=== Servlet containers
The following embedded servlet containers are supported out of the box:

|===
|Name |Servlet Version |Java Version

|Tomcat 8
|3.1
|Java 7+

|Tomcat 7
|3.0
|Java 6+

|Jetty 9.3
|3.1
|Java 8+

|Jetty 9.2
|3.1
|Java 7+

|Jetty 8
|3.0
|Java 6+

|Undertow 1.3
|3.1
|Java 7+
|===

You can also deploy Spring Boot applications to any Servlet 3.0+ compatible container.



