include::ROOT:partial$attributes.adoc[]
[[boot-features-hazelcast]]
== Hazelcast

If Hazelcast is on the classpath, Spring Boot will auto-configure a `HazelcastInstance`
that you can inject in your application. The `HazelcastInstance` is only created if a
configuration is found.

You can define a `com.hazelcast.config.Config` bean and we'll use that. If your
configuration defines an instance name, we'll try to locate an existing instance rather
than creating a new one.

You could also specify the `hazelcast.xml` configuration file to use via configuration:

[source,properties,indent=0]
----
	spring.hazelcast.config=classpath:config/my-hazelcast.xml
----

Otherwise, Spring Boot tries to find the Hazelcast configuration from the default
locations, that is `hazelcast.xml` in the working directory or at the root of the
classpath. We also check if the `hazelcast.config` system property is set. Check the
http://docs.hazelcast.org/docs/latest/manual/html-single/[Hazelcast documentation] for
more details.

NOTE: Spring Boot also has an
<<boot-features-caching-provider-hazelcast,explicit caching support for Hazelcast>>. The
`HazelcastInstance` is automatically wrapped in a `CacheManager` implementation if
caching is enabled.



