include::ROOT:partial$attributes.adoc[]
[[common-application-properties]]

Various properties can be specified inside your `application.properties` file, inside your `application.yml` file, or as command line switches.
This appendix provides a list of common Spring Boot properties and references to the underlying classes that consume them.

TIP: Spring Boot provides various conversion mechanism with advanced value formatting, make sure to review xref:spring-boot-reference-documentation:boot-features.adoc#boot-features-external-config-conversion[ the properties conversion section].

NOTE: Property contributions can come from additional jar files on your classpath, so you should not consider this an exhaustive list.
Also, you can define your own properties.


== Core properties

== Cache properties

== Mail properties

== JSON properties

== Data properties

== Transaction properties

== Data migration properties

== Integration properties

== Web properties

== Templating properties

== Server properties

== Security properties

== RSocket properties

== Actuator properties

== Devtools properties

== Testing properties
